CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TYPE task_hours AS ENUM ('MORNING', 'AFTERNOON', 'EVENING');

CREATE TYPE task_status AS ENUM ('NOT_STARTED', 'IN_PROGRESS', 'DONE');

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tasks (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID FOREIGN KEY REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(55) UNIQUE NOT NULL,
  description VARCHAR(255),
  hour task_hours NOT NULL,
  status task_status NOT NULL DEFAULT 'NOT_STARTED',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);